[package]
name = "mles-utils"
version = "0.6.0"
authors = ["jq-rs"]
description = "Mles-utils for Mles server and clients"
license = "GPL-3.0"
repository = "https://github.com/jq-rs/mles-rs"

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_cbor = "0.5"
byteorder = "1.0.0"
siphasher = "0.2"
 
[lib]
test = true
