[package]
name = "mles-client"
version = "0.9.10"
authors = ["jq-rs"]
description = "Mles-client, a distributed data protocol example (chat) client"
license = "GPL-3.0"
repository = "https://github.com/jq-rs/mles-rs"
documentation = "http://mles.io"
readme = "../README.md"
categories = ["network-programming"]
keywords = ["mles", "publish", "subscribe", "network", "cbor"]

[dependencies]
mles-utils = "0.9"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
bytes = "0.4"
tokio-proto = "0.1"
tokio-service = "0.1"
tungstenite = "0.2"
tokio-tungstenite = "0.1"

[badges]
travis-ci = { repository = "jq-rs/mles-rs" }
appveyor = { repository = "jq-rs/mles-rs" }
